/**
 * Field is the shared label + hint + error wrapper for every admin form
 * primitive. Mirrors design_handoff_portfolio/design/admin/admin-shared.jsx
 * lines 56 to 64 (.f, label, .hint) and adds the inline error slot called
 * for by issue #46. The layout (column flex, gap 6px, monospace caps label
 * with right-aligned hint) is copied verbatim from
 * design_handoff_portfolio/design/admin.css lines 185 to 205.
 *
 * The composing primitive (TextField, TextArea, MarkdownField,
 * VisibilityToggle) is responsible for rendering the actual input and
 * wiring `aria-describedby` to the ids exposed by this wrapper. The Vercel
 * `composition-patterns` skill is the headliner: ten editor sections share
 * these primitives, so the surface stays narrow and the wrapper is the
 * single owner of the label/hint/error DOM shape.
 */
import type { ReactNode } from 'react';

export type FieldProps = {
  /** Identifier of the input controlled by this field. Used to associate
   *  the label, hint, and error nodes with the input via `htmlFor` and
   *  `aria-describedby`. */
  id: string;
  /** The visible label text. Rendered uppercase mono per the design. */
  label: string;
  /** Optional helper text shown to the right of the label. */
  hint?: string | undefined;
  /** Inline validation message. When present, the field is treated as
   *  invalid: the message is rendered with `role="alert"` so screen readers
   *  announce it on first paint, and the host input picks up
   *  `aria-invalid="true"` plus the error id in `aria-describedby`. */
  error?: string | undefined;
  /** The input element. The composing primitive passes ids generated by
   *  this wrapper through `renderInput` so the a11y wiring is centralised
   *  here, not duplicated per primitive. */
  renderInput: (ids: {
    inputId: string;
    describedBy: string | undefined;
    invalid: boolean;
  }) => ReactNode;
};

/**
 * Renders the label + optional hint + composed input + optional error. The
 * `renderInput` render-prop is intentionally narrow: it receives only the
 * ids and invalid flag the input must apply, not the whole field state.
 * That keeps every primitive's surface trivial and lets the wrapper own
 * the a11y contract.
 */
export function Field({ id, label, hint, error, renderInput }: FieldProps) {
  const hintId = hint ? `${id}-hint` : undefined;
  const errorId = error ? `${id}-error` : undefined;
  const describedBy = [hintId, errorId].filter(Boolean).join(' ') || undefined;
  return (
    <div className={`f${error ? ' f-invalid' : ''}`}>
      <label htmlFor={id}>
        {label}
        {hint ? (
          <span className="hint" id={hintId}>
            {hint}
          </span>
        ) : null}
      </label>
      {renderInput({ inputId: id, describedBy, invalid: Boolean(error) })}
      {error ? (
        <p className="f-error" id={errorId} role="alert">
          {error}
        </p>
      ) : null}
    </div>
  );
}
